/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package externalpackage;
import internalpage.*;
import java.awt.*;
import javax.swing.border.Border;
import javax.swing.plaf.basic.BasicInternalFrameUI;


/**
 *
 * @author SCC-PC01
 */
public class dashboardpage1 extends javax.swing.JFrame {

    private BasicInternalFrameUI BasicInternalFrameUI;

    /**
     * Creates new form dashboardpage1
     */
    public dashboardpage1() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0,0, 0));
        BasicInternalFrameUI bi =(BasicInternalFrameUI);
        bi.setNorthPane(null); 
    }
Color navcolor = new Color(51,102,255);
Color headcolor = new Color(0,102,204);
Color bodycolor = new Color(102,102,255);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        nav = new javax.swing.JPanel();
        navuser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        navgrade = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        navclasswork = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        maindesk = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        body.setBackground(new java.awt.Color(102, 102, 255));
        body.setLayout(null);

        nav.setBackground(new java.awt.Color(51, 102, 255));
        nav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navuser.setBackground(new java.awt.Color(51, 102, 255));
        navuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navuserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navuserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navuserMouseExited(evt);
            }
        });
        navuser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User");
        navuser.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, -1));

        nav.add(navuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 153, -1, 43));

        navgrade.setBackground(new java.awt.Color(51, 102, 255));
        navgrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navgradeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navgradeMouseExited(evt);
            }
        });
        navgrade.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Grades");
        navgrade.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, -1));

        nav.add(navgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 207, -1, 43));

        navclasswork.setBackground(new java.awt.Color(51, 102, 255));
        navclasswork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navclassworkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navclassworkMouseExited(evt);
            }
        });
        navclasswork.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Classwork");
        navclasswork.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, 20));

        nav.add(navclasswork, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 261, -1, 43));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("User Name");
        nav.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 106, 140, 29));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(51, 102, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-user-100_1.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, -1));

        nav.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 100));

        body.add(nav);
        nav.setBounds(0, 0, 140, 420);

        header.setBackground(new java.awt.Color(0, 102, 204));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        body.add(header);
        header.setBounds(140, 0, 620, 80);

        maindesk.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout maindeskLayout = new javax.swing.GroupLayout(maindesk);
        maindesk.setLayout(maindeskLayout);
        maindeskLayout.setHorizontalGroup(
            maindeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        maindeskLayout.setVerticalGroup(
            maindeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        body.add(maindesk);
        maindesk.setBounds(140, 80, 620, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void navuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navuserMouseClicked
        userinternal sp = new userinternal();
      maindesk.add(sp).setVisible(true);
       // this.dispose();
    }//GEN-LAST:event_navuserMouseClicked

    private void navuserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navuserMouseEntered
        navuser.setBackground(bodycolor);
    }//GEN-LAST:event_navuserMouseEntered

    private void navuserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navuserMouseExited
        navuser.setBackground(navcolor);
    }//GEN-LAST:event_navuserMouseExited

    private void navgradeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navgradeMouseEntered
        navgrade.setBackground(bodycolor);
    }//GEN-LAST:event_navgradeMouseEntered

    private void navgradeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navgradeMouseExited
        navgrade.setBackground(navcolor);        // TODO add your handling code here:
    }//GEN-LAST:event_navgradeMouseExited

    private void navclassworkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navclassworkMouseEntered
        navclasswork.setBackground(bodycolor);
    }//GEN-LAST:event_navclassworkMouseEntered

    private void navclassworkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navclassworkMouseExited
        navclasswork.setBackground(navcolor);
    }//GEN-LAST:event_navclassworkMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardpage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardpage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardpage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardpage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardpage1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane maindesk;
    private javax.swing.JPanel nav;
    private javax.swing.JPanel navclasswork;
    private javax.swing.JPanel navgrade;
    private javax.swing.JPanel navuser;
    // End of variables declaration//GEN-END:variables

    private void setBorder(Border createEmptyBorder) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
